# Changes here will be overwritten by Copier
_commit: v1.3.3
_src_path: gh:lincc-frameworks/python-project-template
author_email: echarles@slac.stanford.edu
author_name: Eric Charles
create_example_module: false
custom_install: true
include_notebooks: false
module_name: tables_io
mypy_type_checking: none
preferred_linter: pylint
project_license: MIT
project_name: tables-io
use_gitlfs: none
use_isort: false
